# Rust 代码格式化配置
# 更多配置选项: https://rust-lang.github.io/rustfmt/

# 基本设置
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# 导入设置
reorder_imports = true
reorder_modules = true
group_imports = "StdExternalCrate"

# 格式化设置
use_small_heuristics = "Default"
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# 注释和文档
format_code_in_doc_comments = true
format_strings = false
format_macro_matchers = true

# 空格和换行
spaces_around_ranges = false
space_before_colon = false
space_after_colon = true
spaces_within_parens_and_brackets = false

# 其他设置
remove_nested_parens = true
use_field_init_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false

# 导入粒度控制
imports_granularity = "Preserve"

# 尾随逗号
trailing_comma = "Vertical"
trailing_semicolon = true

# 匹配块格式化
match_block_trailing_comma = false

# 链式调用
chain_width = 60
single_line_if_else_max_width = 50

# 错误处理
error_on_line_overflow = false
error_on_unformatted = false

# 实验性功能（需要 nightly 版本）
# unstable_features = true
# normalize_comments = true
# wrap_comments = true
# comment_width = 80
